Try to catch npm error

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,25 +16,10 @@ jobs:
       - run:
           name: "Lint check"
           command: |
-            npm run lint > lintOutput.txt
-            cat lintOutput.txt
-
-            problems=`echo grep -c 'problems' lintOutput.txt | wc -l`
-            echo $problems
-
-            if [ $problems -gt 0 ]; then
-              errorString=$(cat lintOutput.txt | grep problems | grep -Eoh "\([0-9]*")
-              errorCount=`echo ${errorString/\(/''}`
-
-              if [[ $errorCount -gt 0 ]]; then
-                cat lintOutput.txt
-
-                echo "$errorCount errors were found while checking linting. Please fix linting errors."
-                echo "You can run 'npm run lint' or 'npm run lintFix' script. 'npm run lintFix' will automatic fix your formatting errors"
-                
-                rm lintOutput.txt
-                exit 1
-              fi 
+            if npm run lint | grep -q 'npm ERR!'; then
+              echo "Errors were found while checking linting. Please fix linting errors."
+              echo "You can run 'npm run lint' or 'npm run lintFix' script. 'npm run lintFix' will automatic fix your formatting errors"
+              exit 1
             fi
             
             echo "Linting check pass"
